FROM goboring/golang:1.16.7b7

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./
COPY start.sh ./

RUN env GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o ./hashapi

EXPOSE 9000

CMD [ "./start.sh" ]